GET http://localhost:3001/users

###GET users by id

GET http://localhost:3001/users/650d08d1031728b5ee8722b7

### Create Contact
POST http://localhost:3001/users HTTP/1.1
Content-type: aplication/json

{
    "name": "example",
    "lastname": "example2",
    "email": "test@example.com",
    "favorite_color": "casas",
    "birthdate": "10-08-1991"
}

###PUT contact

PUT http://localhost:3001/users/65069a5eefe0b005eea1a5af HTTP/1.1
Content-type: application/json

{
    "name": "example",
    "lastname": "example2",
    "email": "test@example.com",
    "favorite_color": "casas",
    "birthdate": "10-08-1991"
}

### DELETE contact

DELETE http://localhost:3001/users/65069a5eefe0b005eea1a5af HTTP/1.1